services:
  db:
    # container_name: mariadb
    image: mariadb:10.11
    restart: always

    environment:
      MYSQL_DATABASE: mini_chat
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  app:
    build: .
    depends_on:
      - db
      - phpmyadmin
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - DATABASE=mini_chat
    ports:
      - 8001:80